services:
  postgres:
    image: postgres
    volumes:
      - ./BaseAmilPostgres.sql:/docker-entrypoint-initdb.d/1-baseamil.sql
      - ./schema-postgresql.sql:/docker-entrypoint-initdb.d/2-schema-postgresql.sql
    environment:
      POSTGRES_PASSWORD: "Postgres2025!"
    ports:
      - "5432:5432"
  mysql:
    image: mysql:9.0
    volumes:
      - ./BaseAmilMySql.sql:/docker-entrypoint-initdb.d/1-baseamil.sql
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2025!"
      MYSQL_DATABASE: "baseamil"
    ports:
      - "3306:3306"